language: php
php:
    - 5.3
    - 5.4
before_script:
    - mysql -e 'create database wp_tests;'
    - mkdir -p ~/src
    - git clone https://github.com/nb/wordpress-tests.git ~/src
    - git clone git://gist.github.com/3404014.git ~/src/wordpress-tests
    - wget http://wordpress.org/latest.tar.gz ~/src
    - tar zxvf ~/src/latest.tar.gz
    - cp -r ~/builds/fubralimited/CDN-Sync-Tool ~/src/wordpress/wp-content/plugins/
branches:
    only:
        - tests
script: phpunit --exclude-group connection